/*
Copyright IBM Corp. All Rights Reserved.

SPDX-License-Identifier: Apache-2.0
*/

package mimc_test

import (
	"fmt"
	"testing"

	"github.com/consensys/gnark-crypto/ecc"
	"github.com/consensys/gnark-crypto/ecc/bls12-381/fr"

	"github.com/consensys/gnark/frontend"
	"github.com/consensys/gnark/frontend/cs/r1cs"

	"github.com/stretchr/testify/require"

	"github.com/LFDT-Panurus/panurus/x/token/core/zkatsnark/circuit/gadgets"
	"github.com/LFDT-Panurus/panurus/x/token/core/zkatsnark/crypto/mimc"
)

// TestHashDeterminism verifies that two calls with identical inputs produce
// identical outputs. Non-determinism here means a state initialisation bug.
func TestHashDeterminism(t *testing.T) {
	var a, b, c fr.Element
	a.SetUint64(42)
	b.SetUint64(1337)
	c.SetUint64(9999)

	out1, err := mimc.Hash(a, b, c)
	require.NoError(t, err)

	out2, err := mimc.Hash(a, b, c)
	require.NoError(t, err)

	require.Equal(t, out1.Bytes(), out2.Bytes(),
		"identical inputs must produce identical outputs every time")
}

// TestHashDifferentInputs verifies that changing any input changes the output.
// Catches bugs where one input position has no effect on the output.
func TestHashDifferentInputs(t *testing.T) {
	var a, b, c fr.Element
	a.SetUint64(1)
	b.SetUint64(2)
	c.SetUint64(3)

	var bPrime fr.Element
	bPrime.SetUint64(99)

	out1, _ := mimc.Hash(a, b, c)
	out2, _ := mimc.Hash(a, bPrime, c)
	require.NotEqual(t, out1.Bytes(), out2.Bytes(),
		"changing input[1] must change the output")

	var aPrime fr.Element
	aPrime.SetUint64(55)
	out3, _ := mimc.Hash(aPrime, b, c)
	require.NotEqual(t, out1.Bytes(), out3.Bytes(),
		"changing input[0] must change the output")

	var cPrime fr.Element
	cPrime.SetUint64(77)
	out4, _ := mimc.Hash(a, b, cPrime)
	require.NotEqual(t, out1.Bytes(), out4.Bytes(),
		"changing input[2] must change the output")
}

// TestHashLengthSeparation verifies that hashing different numbers of
// field elements produces different outputs.
// MiMC hashes inputs sequentially using the Miyaguchi–Preneel construction,
// so Hash(a), Hash(a,b), and Hash(a,b,c) must produce distinct digests.
func TestHashLengthSeparation(t *testing.T) {
	var a, b, c fr.Element
	a.SetUint64(7)
	b.SetUint64(13)
	c.SetUint64(17)

	out1, _ := mimc.Hash(a)
	out2, _ := mimc.Hash(a, b)
	out3, _ := mimc.Hash(a, b, c)

	require.NotEqual(t, out1.Bytes(), out2.Bytes(),
		"Hash(a) must differ from Hash(a, b)")
	require.NotEqual(t, out2.Bytes(), out3.Bytes(),
		"Hash(a, b) must differ from Hash(a, b, c)")
	require.NotEqual(t, out1.Bytes(), out3.Bytes(),
		"Hash(a) must differ from Hash(a, b, c)")
}

// TestHashInputCountBoundaries verifies error handling for invalid input counts.
func TestHashInputCountBoundaries(t *testing.T) {
	_, err := mimc.Hash()
	require.Error(t, err, "zero inputs must return an error")
	require.ErrorIs(t, err, mimc.ErrInvalidInputCount)

	tooMany := make([]fr.Element, 4)
	_, err = mimc.Hash(tooMany...)
	require.Error(t, err, "4 inputs exceeds MaxInputs=3 and must return an error")
	require.ErrorIs(t, err, mimc.ErrInvalidInputCount)

	// Boundary: exactly 3 inputs must succeed.
	var a, b, c fr.Element
	a.SetUint64(1)
	b.SetUint64(2)
	c.SetUint64(3)
	_, err = mimc.Hash(a, b, c)
	require.NoError(t, err, "exactly 3 inputs must succeed")
}

// TestHashKnownVector is the ground-truth test.
// The expected value was generated by running a temporary scratch program
// which calls gnark-crypto's mimc directly with inputs {1, 2, 3}.
// If this test fails, the native hashing logic has changed or the
// implementation no longer matches gnark-crypto's MiMC reference
// implementation.
func TestHashKnownVector(t *testing.T) {
	var a, b, c fr.Element
	a.SetUint64(1)
	b.SetUint64(2)
	c.SetUint64(3)

	out, err := mimc.Hash(a, b, c)
	require.NoError(t, err)

	// This is the hex string of the hash which was calculated in a temporary
	// go program using mimc(1, 2, 3) and the result printed to the terminal
	expectedHex := "1618589b3fafe01e2080a4796148349cdcf5b830b2f2ac5c1b34aa62be38ae2b"
	actualHex := fmt.Sprintf("%x", out.Bytes())

	require.Equal(t, expectedHex, actualHex,
		"hash output does not match known reference value; "+
			"check state initialization and output element index in hash.go")
}

//--------------------------------------Cross Consistency Tests-------------------------------------//

// mimcTestCircuit is a minimal circuit that computes MiMC over its inputs
// and constrains the result to equal a public output variable.
// Used only in cross-consistency tests and not part of the production circuit layer.
type mimcTestCircuit struct {
	// NumInputs is baked into the circuit at compile time.
	// A separate circuit instance is compiled per input count.
	NumInputs int

	// Inputs: only indices 0..NumInputs-1 are used.
	In0 frontend.Variable
	In1 frontend.Variable
	In2 frontend.Variable

	// Out is the public output, i.e. the expected hash value.
	// Setting this to the native hash result and checking IsSolved()
	// verifies that the circuit computes the same value.
	Out frontend.Variable `gnark:",public"`
}

func (c *mimcTestCircuit) Define(api frontend.API) error {
	inputs := make([]frontend.Variable, c.NumInputs)
	allInputs := []frontend.Variable{c.In0, c.In1, c.In2}
	for i := range c.NumInputs {
		inputs[i] = allInputs[i]
	}

	result, err := gadgets.HashCircuit(api, inputs...)
	if err != nil {
		return err
	}

	// If the native hash and the circuit hash agree, this constraint is satisfied.
	// If they disagree, IsSolved() will report this specific constraint as failing.
	api.AssertIsEqual(result, c.Out)

	return nil
}

// TestMimcCrossConsistency is the mandatory gate test.
//
// It compiles a small circuit for each input count (1, 2, 3), then runs
// 50 random inputs through both the native Hash function and the circuit
// gadget via gnark's constraint solver, and compares the outputs byte-for-byte.
//
// A failure means one of:
//
//	(a) The circuit gadget uses different round constants than the native code
//	(b) The input ordering differs between native WriteElement() and circuit Write()
//	(c) The initial state differs (native starts at h=0; circuit must also start at 0)
//	(d) The output extraction differs (native returns SumElement(); circuit returns Sum())
//
// This test MUST pass before SpendCircuit, OutputCircuit, or MigrationCircuit are written.
func TestMimcCrossConsistency(t *testing.T) {
	for _, numInputs := range []int{1, 2, 3} {
		t.Run(fmt.Sprintf("%d_inputs", numInputs), func(t *testing.T) {
			t.Parallel()

			// Compile a fresh circuit for this input count.
			// The circuit shape is determined by NumInputs at compile time.
			circuitTemplate := &mimcTestCircuit{NumInputs: numInputs}
			cs, err := frontend.Compile(
				ecc.BLS12_381.ScalarField(),
				r1cs.NewBuilder,
				circuitTemplate,
			)
			require.NoError(t, err,
				"circuit compilation failed for %d inputs", numInputs)

			for trial := range 50 {
				// Generate random field elements for this trial.
				var in0, in1, in2 fr.Element
				_, _ = in0.SetRandom()
				_, _ = in1.SetRandom()
				_, _ = in2.SetRandom()

				activeInputs := []fr.Element{in0, in1, in2}[:numInputs]

				// Compute the expected output using the native Hash function.
				nativeOut, err := mimc.Hash(activeInputs...)
				require.NoError(t, err,
					"trial %d: native Hash returned an error", trial)

				// Build the circuit assignment.
				// Out is set to the native result. If the circuit computes the
				// same value, the AssertIsEqual constraint in Define() is satisfied
				// and IsSolved() returns nil. If values differ, IsSolved() returns
				// an error identifying the failing constraint.
				assignment := &mimcTestCircuit{
					NumInputs: numInputs,
					In0:       0,
					In1:       0,
					In2:       0,
					Out:       nativeOut,
				}

				// Set only the active inputs.
				allVars := []*frontend.Variable{&assignment.In0, &assignment.In1, &assignment.In2}
				for i := range numInputs {
					*allVars[i] = activeInputs[i]
				}

				// Build witness and check constraint satisfaction.
				witness, err := frontend.NewWitness(assignment, ecc.BLS12_381.ScalarField())
				require.NoError(t, err,
					"trial %d: witness construction failed", trial)

				err = cs.IsSolved(witness)
				require.NoError(t, err,
					"trial %d, %d inputs: CROSS-CONSISTENCY FAILURE\n"+
						"The native MiMC and the circuit MiMC gadget computed different values.\n"+
						"in0=%x\nin1=%x\nin2=%x\nnative output=%x\n"+
						"Check that HashCircuit uses h.Write(inputs...) then h.Sum(),\n"+
						"and that Hash uses WriteElement(x) for each x then SumElement().",
					trial, numInputs,
					in0.Bytes(), in1.Bytes(), in2.Bytes(),
					nativeOut.Bytes(),
				)
			}
		})
	}
}
